<% n = nginx.nginx %>
daemon <% return n.daemon %>;
pid <% return n.pid %>;
worker_processes <% return n.workers %>;
error_log <% return n.error_log %> info;

events {}

http {

  include <% return openresty_dir %>/nginx/conf/mime.types;

  access_log <% return n.access_log %>;

  lua_package_path "<% return lua_package_path %>";
  lua_package_cpath "<% return lua_package_cpath %>";

  init_by_lua_file <% return modules["tokuboilerplate.web.init"] %>;

  server {

    listen <% return n.port %>;
    server_name <% return n.domain %>;

    location = / {
      limit_except GET { deny all; }
      root public;
      try_files /<% return hashed("index.html") %> =404;
      add_header Cache-Control 'private, max-age=60';
    }

    location = /sync {
      limit_except POST { deny all; }
      content_by_lua_file <% return modules["tokuboilerplate.web.sync"] %>;
    }

    location ~* "\.[a-f0-9]{12}\." {
      limit_except GET { deny all; }
      root public;
      expires 1y;
      add_header Cache-Control "public, immutable";
    }

  }
}
